"""Curated list of supported Ollama model configurations."""

from __future__ import annotations

from llm_reliability.models.model_info import ModelInfo

SUPPORTED_OLLAMA_MODELS: list[ModelInfo] = [
    # ----------------------------------------------------------------------- #
    # Llama family (Meta)
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="Llama",
        name="Llama 3.2 1B",
        parameters="1B",
        parameter_count=1.0,
        context_window=131072,
        recommended_ram_gb=2.0,
        recommended_vram_gb=1.0,
        ollama_identifier="llama3.2:1b",
    ),
    ModelInfo(
        family="Llama",
        name="Llama 3.2 3B",
        parameters="3B",
        parameter_count=3.0,
        context_window=131072,
        recommended_ram_gb=4.0,
        recommended_vram_gb=3.0,
        ollama_identifier="llama3.2:3b",
    ),
    ModelInfo(
        family="Llama",
        name="Llama 3.1 8B",
        parameters="8B",
        parameter_count=8.0,
        context_window=131072,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="llama3.1:8b",
    ),
    ModelInfo(
        family="Llama",
        name="Llama 3.1 70B",
        parameters="70B",
        parameter_count=70.0,
        context_window=131072,
        recommended_ram_gb=48.0,
        recommended_vram_gb=40.0,
        ollama_identifier="llama3.1:70b",
    ),
    ModelInfo(
        family="Llama",
        name="Llama 3 8B",
        parameters="8B",
        parameter_count=8.0,
        context_window=8192,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="llama3:8b",
    ),
    ModelInfo(
        family="Llama",
        name="Llama 3 70B",
        parameters="70B",
        parameter_count=70.0,
        context_window=8192,
        recommended_ram_gb=48.0,
        recommended_vram_gb=40.0,
        ollama_identifier="llama3:70b",
    ),
    ModelInfo(
        family="Llama",
        name="Llama 2 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=4096,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="llama2:7b",
    ),
    ModelInfo(
        family="Llama",
        name="Llama 2 13B",
        parameters="13B",
        parameter_count=13.0,
        context_window=4096,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="llama2:13b",
    ),
    ModelInfo(
        family="Llama",
        name="Code Llama 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=16384,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="codellama:7b",
    ),
    ModelInfo(
        family="Llama",
        name="Code Llama 13B",
        parameters="13B",
        parameter_count=13.0,
        context_window=16384,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="codellama:13b",
    ),
    ModelInfo(
        family="Llama",
        name="Code Llama 34B",
        parameters="34B",
        parameter_count=34.0,
        context_window=16384,
        recommended_ram_gb=24.0,
        recommended_vram_gb=20.0,
        ollama_identifier="codellama:34b",
    ),
    # ----------------------------------------------------------------------- #
    # Qwen family (Alibaba)
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 0.5B",
        parameters="0.5B",
        parameter_count=0.5,
        context_window=131072,
        recommended_ram_gb=1.0,
        recommended_vram_gb=0.5,
        ollama_identifier="qwen2.5:0.5b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 1.5B",
        parameters="1.5B",
        parameter_count=1.5,
        context_window=131072,
        recommended_ram_gb=2.0,
        recommended_vram_gb=1.5,
        ollama_identifier="qwen2.5:1.5b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 3B",
        parameters="3B",
        parameter_count=3.0,
        context_window=131072,
        recommended_ram_gb=4.0,
        recommended_vram_gb=3.0,
        ollama_identifier="qwen2.5:3b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=131072,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="qwen2.5:7b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 14B",
        parameters="14B",
        parameter_count=14.0,
        context_window=131072,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="qwen2.5:14b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 32B",
        parameters="32B",
        parameter_count=32.0,
        context_window=131072,
        recommended_ram_gb=24.0,
        recommended_vram_gb=20.0,
        ollama_identifier="qwen2.5:32b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 72B",
        parameters="72B",
        parameter_count=72.0,
        context_window=131072,
        recommended_ram_gb=48.0,
        recommended_vram_gb=42.0,
        ollama_identifier="qwen2.5:72b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 Coder 1.5B",
        parameters="1.5B",
        parameter_count=1.5,
        context_window=32768,
        recommended_ram_gb=2.0,
        recommended_vram_gb=1.5,
        ollama_identifier="qwen2.5-coder:1.5b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 Coder 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=32768,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="qwen2.5-coder:7b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 Coder 14B",
        parameters="14B",
        parameter_count=14.0,
        context_window=32768,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="qwen2.5-coder:14b",
    ),
    ModelInfo(
        family="Qwen",
        name="Qwen 2.5 Coder 32B",
        parameters="32B",
        parameter_count=32.0,
        context_window=32768,
        recommended_ram_gb=24.0,
        recommended_vram_gb=20.0,
        ollama_identifier="qwen2.5-coder:32b",
    ),
    # ----------------------------------------------------------------------- #
    # Gemma family (Google)
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="Gemma",
        name="Gemma 2 2B",
        parameters="2B",
        parameter_count=2.0,
        context_window=8192,
        recommended_ram_gb=4.0,
        recommended_vram_gb=2.0,
        ollama_identifier="gemma2:2b",
    ),
    ModelInfo(
        family="Gemma",
        name="Gemma 2 9B",
        parameters="9B",
        parameter_count=9.0,
        context_window=8192,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="gemma2:9b",
    ),
    ModelInfo(
        family="Gemma",
        name="Gemma 2 27B",
        parameters="27B",
        parameter_count=27.0,
        context_window=8192,
        recommended_ram_gb=24.0,
        recommended_vram_gb=18.0,
        ollama_identifier="gemma2:27b",
    ),
    ModelInfo(
        family="Gemma",
        name="CodeGemma 2B",
        parameters="2B",
        parameter_count=2.0,
        context_window=8192,
        recommended_ram_gb=4.0,
        recommended_vram_gb=2.0,
        ollama_identifier="codegemma:2b",
    ),
    ModelInfo(
        family="Gemma",
        name="CodeGemma 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=8192,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="codegemma:7b",
    ),
    # ----------------------------------------------------------------------- #
    # Phi family (Microsoft)
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="Phi",
        name="Phi-3 Mini 3.8B",
        parameters="3.8B",
        parameter_count=3.8,
        context_window=131072,
        recommended_ram_gb=4.0,
        recommended_vram_gb=3.0,
        ollama_identifier="phi3:3.8b",
    ),
    ModelInfo(
        family="Phi",
        name="Phi-3 Medium 14B",
        parameters="14B",
        parameter_count=14.0,
        context_window=131072,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="phi3:14b",
    ),
    ModelInfo(
        family="Phi",
        name="Phi-3.5 Mini 3.8B",
        parameters="3.8B",
        parameter_count=3.8,
        context_window=131072,
        recommended_ram_gb=4.0,
        recommended_vram_gb=3.0,
        ollama_identifier="phi3.5:3.8b",
    ),
    ModelInfo(
        family="Phi",
        name="Phi-4 14B",
        parameters="14B",
        parameter_count=14.0,
        context_window=131072,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="phi4:14b",
    ),
    ModelInfo(
        family="Phi",
        name="Phi-4 Mini 3.8B",
        parameters="3.8B",
        parameter_count=3.8,
        context_window=131072,
        recommended_ram_gb=4.0,
        recommended_vram_gb=3.0,
        ollama_identifier="phi4-mini:3.8b",
    ),
    # ----------------------------------------------------------------------- #
    # Mistral family (Mistral AI)
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="Mistral",
        name="Mistral 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=32768,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="mistral:7b",
    ),
    ModelInfo(
        family="Mistral",
        name="Mixtral 8x7B",
        parameters="46.7B",
        parameter_count=46.7,
        context_window=32768,
        recommended_ram_gb=32.0,
        recommended_vram_gb=24.0,
        ollama_identifier="mixtral:8x7b",
    ),
    ModelInfo(
        family="Mistral",
        name="Mistral Nemo 12B",
        parameters="12B",
        parameter_count=12.0,
        context_window=131072,
        recommended_ram_gb=12.0,
        recommended_vram_gb=8.0,
        ollama_identifier="mistral-nemo:12b",
    ),
    # ----------------------------------------------------------------------- #
    # DeepSeek family
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="DeepSeek",
        name="DeepSeek R1 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=131072,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="deepseek-r1:7b",
    ),
    ModelInfo(
        family="DeepSeek",
        name="DeepSeek R1 14B",
        parameters="14B",
        parameter_count=14.0,
        context_window=131072,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="deepseek-r1:14b",
    ),
    ModelInfo(
        family="DeepSeek",
        name="DeepSeek R1 32B",
        parameters="32B",
        parameter_count=32.0,
        context_window=131072,
        recommended_ram_gb=24.0,
        recommended_vram_gb=20.0,
        ollama_identifier="deepseek-r1:32b",
    ),
    ModelInfo(
        family="DeepSeek",
        name="DeepSeek R1 70B",
        parameters="70B",
        parameter_count=70.0,
        context_window=131072,
        recommended_ram_gb=48.0,
        recommended_vram_gb=40.0,
        ollama_identifier="deepseek-r1:70b",
    ),
    ModelInfo(
        family="DeepSeek",
        name="DeepSeek Coder V2",
        parameters="16B",
        parameter_count=16.0,
        context_window=131072,
        recommended_ram_gb=16.0,
        recommended_vram_gb=12.0,
        ollama_identifier="deepseek-coder-v2:16b",
    ),
    # ----------------------------------------------------------------------- #
    # Small / Efficient models
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="TinyLlama",
        name="TinyLlama 1.1B",
        parameters="1.1B",
        parameter_count=1.1,
        context_window=2048,
        recommended_ram_gb=2.0,
        recommended_vram_gb=1.0,
        ollama_identifier="tinyllama:latest",
    ),
    ModelInfo(
        family="SmolLM",
        name="SmolLM2 1.7B",
        parameters="1.7B",
        parameter_count=1.7,
        context_window=8192,
        recommended_ram_gb=2.0,
        recommended_vram_gb=1.5,
        ollama_identifier="smollm2:1.7b",
    ),
    ModelInfo(
        family="Falcon",
        name="Falcon3 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=8192,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="falcon3:7b",
    ),
    # ----------------------------------------------------------------------- #
    # Other families
    # ----------------------------------------------------------------------- #
    ModelInfo(
        family="Yi",
        name="Yi 6B",
        parameters="6B",
        parameter_count=6.0,
        context_window=4096,
        recommended_ram_gb=8.0,
        recommended_vram_gb=5.0,
        ollama_identifier="yi:6b",
    ),
    ModelInfo(
        family="Yi",
        name="Yi 9B",
        parameters="9B",
        parameter_count=9.0,
        context_window=4096,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="yi:9b",
    ),
    ModelInfo(
        family="Yi",
        name="Yi Coder 1.5B",
        parameters="1.5B",
        parameter_count=1.5,
        context_window=16384,
        recommended_ram_gb=2.0,
        recommended_vram_gb=1.5,
        ollama_identifier="yi-coder:1.5b",
    ),
    ModelInfo(
        family="Yi",
        name="Yi Coder 9B",
        parameters="9B",
        parameter_count=9.0,
        context_window=16384,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="yi-coder:9b",
    ),
    ModelInfo(
        family="OpenChat",
        name="OpenChat 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=8192,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="openchat:7b",
    ),
    ModelInfo(
        family="NeuralChat",
        name="Neural Chat 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=8192,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="neural-chat:7b",
    ),
    ModelInfo(
        family="StarCoder2",
        name="StarCoder2 3B",
        parameters="3B",
        parameter_count=3.0,
        context_window=16384,
        recommended_ram_gb=4.0,
        recommended_vram_gb=3.0,
        ollama_identifier="starcoder2:3b",
    ),
    ModelInfo(
        family="StarCoder2",
        name="StarCoder2 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=16384,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="starcoder2:7b",
    ),
    ModelInfo(
        family="StarCoder2",
        name="StarCoder2 15B",
        parameters="15B",
        parameter_count=15.0,
        context_window=16384,
        recommended_ram_gb=16.0,
        recommended_vram_gb=10.0,
        ollama_identifier="starcoder2:15b",
    ),
    ModelInfo(
        family="Falcon",
        name="Falcon 7B",
        parameters="7B",
        parameter_count=7.0,
        context_window=2048,
        recommended_ram_gb=8.0,
        recommended_vram_gb=6.0,
        ollama_identifier="falcon:7b",
    ),
    ModelInfo(
        family="DBRX",
        name="DBRX 132B",
        parameters="132B",
        parameter_count=132.0,
        context_window=32768,
        recommended_ram_gb=96.0,
        recommended_vram_gb=80.0,
        ollama_identifier="dbrx:132b",
    ),
]
