"""Model definitions for all supported LLM providers with unique identifiers."""

from __future__ import annotations

from llm_reliability.models.model_info import ModelInfo


def _m(
    provider: str,
    family: str,
    name: str,
    params: str,
    param_count: float,
    ctx: int,
    runtime: str,
    model_id: str,
) -> ModelInfo:
    return ModelInfo(
        family=family,
        name=name,
        parameters=params,
        parameter_count=param_count,
        context_window=ctx,
        provider=provider,
        runtime=runtime,
        ollama_identifier=f"{provider}:{model_id}",
    )


SUPPORTED_PROVIDER_MODELS: list[ModelInfo] = [
    _m("openai", "OpenAI", "GPT-4.1", "unknown", 0, 128000, "gpt", "gpt-4.1"),
    _m("openai", "OpenAI", "GPT-4.1 Mini", "unknown", 0, 128000, "gpt", "gpt-4.1-mini"),
    _m("openai", "OpenAI", "GPT-4.1 Nano", "unknown", 0, 128000, "gpt", "gpt-4.1-nano"),
    _m("openai", "OpenAI", "GPT-4o", "unknown", 0, 128000, "gpt", "gpt-4o"),
    _m("openai", "OpenAI", "GPT-4o Mini", "unknown", 0, 128000, "gpt", "gpt-4o-mini"),
    _m("openai", "OpenAI", "o3 Mini", "unknown", 0, 200000, "gpt", "o3-mini"),
    _m("openai", "OpenAI", "o1", "unknown", 0, 200000, "gpt", "o1"),
    _m(
        "anthropic",
        "Anthropic",
        "Claude 3.5 Sonnet",
        "unknown",
        0,
        200000,
        "anthropic",
        "claude-3-5-sonnet-20241022",
    ),
    _m(
        "anthropic",
        "Anthropic",
        "Claude 3.5 Haiku",
        "unknown",
        0,
        200000,
        "anthropic",
        "claude-3-5-haiku-20241022",
    ),
    _m(
        "anthropic",
        "Anthropic",
        "Claude 3 Opus",
        "unknown",
        0,
        200000,
        "anthropic",
        "claude-3-opus-20240229",
    ),
    _m(
        "anthropic",
        "Anthropic",
        "Claude 4 Sonnet",
        "unknown",
        0,
        200000,
        "anthropic",
        "claude-4-sonnet-20250514",
    ),
    _m("google", "Google", "Gemini 2.5 Pro", "unknown", 0, 1048576, "gemini", "gemini-2.5-pro"),
    _m("google", "Google", "Gemini 2.5 Flash", "unknown", 0, 1048576, "gemini", "gemini-2.5-flash"),
    _m("google", "Google", "Gemini 2.0 Flash", "unknown", 0, 1048576, "gemini", "gemini-2.0-flash"),
    _m("deepseek", "DeepSeek", "DeepSeek V3", "671B", 671, 128000, "deepseek", "deepseek-chat"),
    _m("deepseek", "DeepSeek", "DeepSeek R1", "671B", 671, 128000, "deepseek", "deepseek-reasoner"),
    _m("mistral", "Mistral", "Mistral Large", "123B", 123, 128000, "mistral", "mistral-large-2407"),
    _m("mistral", "Mistral", "Mistral Small", "22B", 22, 32000, "mistral", "mistral-small-2409"),
    _m("mistral", "Mistral", "Mistral Nemo", "12B", 12, 128000, "mistral", "open-mistral-nemo"),
    _m("cohere", "Cohere", "Command R+", "104B", 104, 128000, "cohere", "command-r-plus"),
    _m("cohere", "Cohere", "Command R", "35B", 35, 128000, "cohere", "command-r"),
    _m("xai", "xAI", "Grok 2", "unknown", 0, 131072, "xai", "grok-2"),
    _m("xai", "xAI", "Grok 2 Mini", "unknown", 0, 131072, "xai", "grok-2-mini"),
    _m("perplexity", "Perplexity", "Sonar Pro", "unknown", 0, 200000, "perplexity", "sonar-pro"),
    _m("perplexity", "Perplexity", "Sonar", "unknown", 0, 200000, "perplexity", "sonar"),
    _m(
        "together",
        "Together AI",
        "Llama 3.3 70B Turbo",
        "70B",
        70,
        131072,
        "together",
        "Llama-3.3-70B-Instruct-Turbo",
    ),
    _m(
        "together",
        "Together AI",
        "Mixtral 8x22B",
        "141B",
        141,
        65536,
        "together",
        "Mixtral-8x22B-Instruct",
    ),
    _m(
        "groq",
        "Groq",
        "Llama 3.3 70B Versatile",
        "70B",
        70,
        131072,
        "groq",
        "llama-3.3-70b-versatile",
    ),
    _m("groq", "Groq", "Mixtral 8x7B", "47B", 47, 32768, "groq", "mixtral-8x7b-32768"),
    _m(
        "openrouter",
        "OpenRouter",
        "GPT-4o (OpenRouter)",
        "unknown",
        0,
        128000,
        "openrouter",
        "openai/gpt-4o",
    ),
    _m(
        "openrouter",
        "OpenRouter",
        "Claude 3.5 Sonnet (OpenRouter)",
        "unknown",
        0,
        200000,
        "openrouter",
        "anthropic/claude-3.5-sonnet",
    ),
    _m(
        "fireworks",
        "Fireworks",
        "Llama 3.3 70B Instruct (Fireworks)",
        "70B",
        70,
        131072,
        "fireworks",
        "llama-v3p3-70b-instruct",
    ),
    _m(
        "fireworks",
        "Fireworks",
        "Mixtral 8x7B Instruct (Fireworks)",
        "47B",
        47,
        32768,
        "fireworks",
        "mixtral-8x7b-instruct",
    ),
    _m(
        "bedrock",
        "AWS Bedrock",
        "Claude 3.5 Sonnet v2",
        "unknown",
        0,
        200000,
        "bedrock",
        "claude-sonnet-v2",
    ),
    _m("bedrock", "AWS Bedrock", "Claude 3 Haiku", "unknown", 0, 200000, "bedrock", "claude-haiku"),
    _m(
        "vertex",
        "Vertex AI",
        "Gemini 2.5 Pro (Vertex)",
        "unknown",
        0,
        1048576,
        "vertex",
        "gemini-2.5-pro",
    ),
    _m(
        "vertex",
        "Vertex AI",
        "Gemini 2.0 Flash (Vertex)",
        "unknown",
        0,
        1048576,
        "vertex",
        "gemini-2.0-flash",
    ),
    _m(
        "azure_openai",
        "Azure OpenAI",
        "GPT-4o (Azure)",
        "unknown",
        0,
        128000,
        "azure_openai",
        "gpt-4o",
    ),
    _m(
        "azure_openai",
        "Azure OpenAI",
        "GPT-4o Mini (Azure)",
        "unknown",
        0,
        128000,
        "azure_openai",
        "gpt-4o-mini",
    ),
    _m(
        "sambanova",
        "SambaNova",
        "Llama 3.3 70B (SambaNova)",
        "70B",
        70,
        131072,
        "sambanova",
        "Meta-Llama-3.3-70B-Instruct",
    ),
    _m(
        "sambanova",
        "SambaNova",
        "Llama 3.1 8B (SambaNova)",
        "8B",
        8,
        131072,
        "sambanova",
        "Meta-Llama-3.1-8B-Instruct",
    ),
    _m(
        "cerebras",
        "Cerebras",
        "Llama 3.1 8B (Cerebras)",
        "8B",
        8,
        131072,
        "cerebras",
        "llama3.1-8b",
    ),
    _m(
        "cerebras",
        "Cerebras",
        "Llama 3.1 70B (Cerebras)",
        "70B",
        70,
        131072,
        "cerebras",
        "llama3.1-70b",
    ),
    _m(
        "nvidia_nim",
        "NVIDIA NIM",
        "Llama 3.3 70B (NIM)",
        "70B",
        70,
        131072,
        "nim",
        "llama-3.3-70b-instruct",
    ),
    _m(
        "nvidia_nim",
        "NVIDIA NIM",
        "Mixtral 8x22B (NIM)",
        "141B",
        141,
        65536,
        "nim",
        "mixtral-8x22b-instruct",
    ),
    _m("litellm", "LiteLLM", "LiteLLM Proxy", "unknown", 0, 128000, "litellm", "litellm-proxy"),
    _m(
        "litellm",
        "LiteLLM",
        "LiteLLM Claude 3.5 Sonnet",
        "unknown",
        0,
        200000,
        "litellm",
        "claude-3.5-sonnet",
    ),
    _m(
        "sglang",
        "SGLang",
        "Llama 3.3 70B (SGLang)",
        "70B",
        70,
        131072,
        "sglang",
        "Llama-3.3-70B-Instruct",
    ),
    _m(
        "sglang",
        "SGLang",
        "Llama 3.1 8B (SGLang)",
        "8B",
        8,
        131072,
        "sglang",
        "Llama-3.1-8B-Instruct",
    ),
]
