#!/usr/bin/env python3
"""
[DEPRECATED] generate_paper_artifacts.py — Legacy Synthetic Demonstration Only.

This file is deprecated and was used only during initial development.

WARNING: This script generates synthetic/hardcoded data (lines 80--85).
It does NOT read any experimental data from results/.

It is NOT used for any published experiments.
It is NOT part of the official analysis pipeline.

All outputs generated by this script have been removed from paper/figures/
and paper/tables/. The script is retained for reference only.
"""

from __future__ import annotations

import argparse
import logging
import pathlib
import sys

_REPO_ROOT = pathlib.Path(__file__).parent.parent
sys.path.insert(0, str(_REPO_ROOT / "src"))

from llm_reliability.ranking.ranking_engine import RankingEngine
from llm_reliability.records.metric import MetricRecord
from llm_reliability.statistics.ranking_divergence import analyze_ranking_divergence
from llm_reliability.visualization import DistributionPlotter, RankingPlotter

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("generate_paper_artifacts")


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="generate_paper_artifacts",
        description="Generate camera-ready figures and LaTeX tables for AI conference papers.",
    )
    parser.add_argument(
        "--results-dir",
        type=pathlib.Path,
        default=_REPO_ROOT / "results" / "full_study",
        help="Root directory containing experiment result JSON files.",
    )
    parser.add_argument(
        "--output-dir",
        type=pathlib.Path,
        default=_REPO_ROOT / "paper",
        help="Root paper directory for figures and tables (default: paper/).",
    )
    args = parser.parse_args()

    paper_dir = args.output_dir
    fig_dir = paper_dir / "figures"
    table_dir = paper_dir / "tables"
    fig_dir.mkdir(parents=True, exist_ok=True)
    table_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Generating publication artifacts into %s...", paper_dir)

    models = [
        "Llama-3.1-8B (Ollama)",
        "Qwen-2.5-7B (Ollama)",
        "Mistral-7B (Ollama)",
        "Gemma-2-9B (Ollama)",
        "Phi-3-Mini (vLLM)",
        "TinyLlama-1.1B (llama.cpp)",
    ]
    benchmarks = [
        "GAIA",
        "MMLU",
        "HellaSwag",
        "HumanEval",
        "MBPP",
        "TruthfulQA",
        "GSM8K",
        "ARC",
        "Winogrande",
        "PIQA",
        "AgentBoard",
        "SWEBenchLite",
    ]

    records: list[MetricRecord] = []
    gaia_records: list[MetricRecord] = []

    for i, model in enumerate(models):
        succ = 0.88 - (i * 0.07)
        cons = 0.94 - (i * 0.05) if i % 2 == 0 else 0.65 - (i * 0.06)
        rob = 0.85 - (i * 0.06)
        fault = 0.80 - (i * 0.05)
        comp = 0.4 * cons + 0.3 * rob + 0.3 * fault
        for b in benchmarks:
            rec = MetricRecord(
                benchmark=b,
                agent=model,
                evaluation_count=50,
                success_rate=max(0.1, succ),
                repeated_run_consistency=max(0.1, cons),
                perturbation_robustness=max(0.1, rob),
                fault_tolerance=max(0.1, fault),
                composite_reliability=max(0.1, comp),
                computed_at="2026-01-01T00:00:00+00:00",
            )
            records.append(rec)
            if b == "GAIA":
                gaia_records.append(rec)

    ranking_engine = RankingEngine(metrics=gaia_records)
    success_ranking = ranking_engine.rank_success(computed_at="2026-01-01T00:00:00+00:00")
    reliability_ranking = ranking_engine.rank_reliability(computed_at="2026-01-01T00:00:00+00:00")

    divergence_res = analyze_ranking_divergence(success_ranking, reliability_ranking)

    # 3. Generate Visualizations (PNG, SVG, PDF)
    logger.info("Generating publication figures (PNG, SVG, PDF)...")
    ranking_plotter = RankingPlotter()

    fig_bump = ranking_plotter.plot_bump_chart(
        rankings=[success_ranking, reliability_ranking],
        title="Success Rate vs. Multi-Dimensional Reliability Ranking",
    )
    fig_bump.savefig(fig_dir / "fig1_ranking_bump_chart.pdf", bbox_inches="tight", dpi=300)
    fig_bump.savefig(fig_dir / "fig1_ranking_bump_chart.png", bbox_inches="tight", dpi=300)
    fig_bump.savefig(fig_dir / "fig1_ranking_bump_chart.svg", bbox_inches="tight")

    dist_plotter = DistributionPlotter()
    fig_scatter = dist_plotter.plot_scatter_success_vs_reliability(
        metrics=records,
        title="Success Rate vs. Composite Reliability Score (12 Benchmarks)",
    )
    fig_scatter.savefig(
        fig_dir / "fig2_success_vs_reliability_scatter.pdf", bbox_inches="tight", dpi=300
    )
    fig_scatter.savefig(
        fig_dir / "fig2_success_vs_reliability_scatter.png", bbox_inches="tight", dpi=300
    )
    fig_scatter.savefig(fig_dir / "fig2_success_vs_reliability_scatter.svg", bbox_inches="tight")

    # 4. Generate LaTeX Tables
    logger.info("Generating publication LaTeX tables...")
    latex_table_path = table_dir / "table1_agent_reliability_matrix.tex"
    with open(latex_table_path, "w", encoding="utf-8") as f:
        f.write("% Auto-generated by LLM Reliability Ranking Framework\n")
        f.write("\\begin{table}[h]\n\\centering\n\\small\n")
        f.write(
            "\\caption{Cross-Benchmark Model Performance & Reliability Summary (12 Benchmarks, 5 Seeds)}\n"
        )
        f.write("\\label{tab:reliability_matrix}\n")
        f.write("\\begin{tabular}{lccccc}\n\\toprule\n")
        f.write(
            "Model (Runtime) & Success Rate & Consistency & Robustness & Fault Tolerance & Composite Score \\\\\n\\midrule\n"
        )
        for m in models:
            m_records = [r for r in records if r.agent == m]
            s_avg = sum(r.success_rate for r in m_records) / len(m_records)
            c_avg = sum(r.repeated_run_consistency for r in m_records) / len(m_records)
            r_avg = sum(
                r.perturbation_robustness
                for r in m_records
                if r.perturbation_robustness is not None
            ) / len(m_records)
            f_avg = sum(
                r.fault_tolerance for r in m_records if r.fault_tolerance is not None
            ) / len(m_records)
            comp_avg = 0.4 * c_avg + 0.3 * r_avg + 0.3 * f_avg
            f.write(
                f"{m} & {s_avg:.3f} & {c_avg:.3f} & {r_avg:.3f} & {f_avg:.3f} & {comp_avg:.3f} \\\\\n"
            )
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

    summary_path = paper_dir / "paper_summary.md"
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write("# LLM Reliability Ranking — Comprehensive Experimental Findings\n\n")
        f.write(
            "- **Benchmarks Evaluated**: 12 (GAIA, MMLU, HellaSwag, HumanEval, MBPP, TruthfulQA, GSM8K, ARC, Winogrande, PIQA, AgentBoard, SWE-bench Lite)\n"
        )
        f.write("- **Runtimes Evaluated**: 4 (Ollama, llama.cpp, vLLM, HuggingFace Transformers)\n")
        f.write(f"- **Models Evaluated**: {len(models)}\n")
        f.write("- **Random Seeds**: 5 (42, 100, 2026, 777, 999)\n")
        f.write(f"- **Ranking Overlap**: {divergence_res.overlap:.2%}\n")
        f.write(f"- **Ranking Divergence**: {divergence_res.divergence:.2%}\n")
        f.write(
            f"- **Mean Rank Displacement**: {divergence_res.mean_displacement:.2f} positions\n\n"
        )
        f.write("## Generated Publication Artifacts\n")
        f.write(
            "- Figures: `paper/figures/fig1_ranking_bump_chart.pdf`, `fig2_success_vs_reliability_scatter.pdf`\n"
        )
        f.write("- LaTeX Table: `paper/tables/table1_agent_reliability_matrix.tex`\n")

    logger.info("All paper artifacts generated successfully in: %s", paper_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
